
# Be sure to change the environment variables below for DOCKERUSER and DOCKERPASS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: front
        image: gcr.io/conductive-fold-275020/front:latest
        ports:
        - containerPort: 8080
        #- name: DEPLOYED
        #  value: "True"